# ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆå·¦å´ã®è¡¨ç¤º
format = """
$os\
$hostname\
$time\
$battery\
$memory_usage
$directory\
$git_branch\
$git_status\
$git_metrics
$character
"""

# å³å´ã®è¡¨ç¤º
right_format = "$nodejs$bun$ruby"

# OSã‚¢ã‚¤ã‚³ãƒ³ã®è¡¨ç¤º
[os]
disabled = false

# ãƒ›ã‚¹ãƒˆåã®è¡¨ç¤º
[hostname]
ssh_only = false
format = "[$ssh_symbol$hostname]($style) "
style = "bold dimmed red"

# æ™‚åˆ»ã®è¡¨ç¤º
[time]
disabled = false
format = "[$time]($style) "
style = "bold dimmed cyan"

# ãƒãƒƒãƒ†ãƒªãƒ¼çŠ¶æ…‹ã®è¡¨ç¤º
[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

# ãƒãƒƒãƒ†ãƒªãƒ¼è¡¨ç¤ºã®æ¡ä»¶
[[battery.display]]
threshold = 100
style = "bold dimmed yellow"

# ãƒ¡ãƒ¢ãƒªã®åˆ©ç”¨çŠ¶æ…‹ã®è¡¨ç¤º
[memory_usage]
disabled = false
threshold = 0
format = "[$symbol$ram( $percentage%)]($style) "

# ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã®è¡¨ç¤º
[directory]
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "â€¦/"
style = "white"

# ãƒ–ãƒ©ãƒ³ãƒã®è¡¨ç¤º
[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "purple"

# Gitã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ã®è¡¨ç¤º
[git_status]
style = "purple"

# ãƒ¡ãƒˆãƒªã‚¯ã‚¹ã®è¡¨ç¤º
[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"

# rubyã®è¡¨ç¤º
[ruby]
format = "[$symbol($version )]($style) "
style = "red"

# nodeã®è¡¨ç¤º
[nodejs]
format = "[$symbol($version )]($style) "
style = "green"
detect_extensions = ["js", "mjs", "cjs", "ts", "mts", "cts"]
detect_files = ["package.json", ".node-version", ".nvmrc"]
detect_folders = ["node_modules"]

# bunã®è¡¨ç¤º
[bun]
format = "[$symbol($version )]($style) "
style = "bold red"
detect_extensions = ["js", "mjs", "cjs", "ts", "mts", "cts"]
detect_files = ["bun.lockb", "bunfig.toml"]
